### ISSUE TITLE
Feature: Implement IDisposable

### ISSUE THREAD

**Issue by adamhewitt627** [moq/Moq.AutoMocker#102]
There are times that AutoMocker may provide (or be given) an object which implements IDisposable. It would be good if these could be disposed along with the mocker. However, any project with analyzers will get build warnings/errors in their tests because of no longer disposing of the object. So either,
1. A breaking change
2. Some form of an opt-in? `using var mocker = new AutoMocker().AsDisposable();`

**Comment by Keboo** [comment]
Personally on my projects I tend to write a lot of extension methods on AutoMocker to do common setups, so I like option 2. 
I think it might be nice to expose some sort of API to read what is currently registered in AutoMocker to give other people opportunities to expand on the idea.

**Comment by adamhewitt627** [comment]
I like option 2 better as well, though it leaves me with a couple questions:
1. What should `var` be, especially to a consumer who doesn't like/use the implicit type. (Also thinking about wanting to compose these together - `new AutoMocker().WithServiceProvider().AsDisposable();`)
2. Should this live in AM, or maybe a new Extensions project?

**Comment by adamhewitt627** [comment]
Possibly something along the lines of:
```cs
public interface IAutoMocker : IDisposable
{
    // Get, GetMock, Setup, etc.
}

internal class AutoMockerDisposble
{
    AutoMockerDisposble(AutoMocker @delegateTo) { }
}

public static IAutoMocker AsDisposable(this AutoMocker mocker) => new AutoMockerDisposble(mocker);
```

**Comment by Keboo** [comment]
I think I would drop the fluent syntax; the rest of the AutoMocker API is not fluent so it looks out of place IMO.

I would do it more like this:
```C#
public static IDisposable AsDisposable(this AutoMocker mocker) => new AutoMockerDisposble(mocker);
```

Somewhat related do we want to add another TFM for .NET5.0, and do an AsAsyncDisposable() method as well?

**Comment by adamhewitt627** [comment]
So, consumption would look like:
```cs
AutoMocker mocker = new();
using (mocker.AsDisposable())
{
}
```

I'm good with the async disposable too, but not sure what it has to do with .NET5.

**Comment by Keboo** [comment]
Yea, or updating for C# 8 syntax.
```C#
AutoMocker moker = new();
using mocker.AsDisposable();
```

The reason for the TFM is the IAsyncDisposable interface requires a NuGet package on older TFMs and built-in on newer ones. Looking again, It looks like it was added in the netcore3.x not NET 5, but in either case we would need to do something like:
- Add the newer TFM to pick up the interface
- Conditionally bring in the NuGet package for older TFMs
- Ensure that condition propagates into NuGet dependencies (open question; are we ok taking a NuGet dependency here?)
