### ISSUE TITLE
TypeLoadException when using CreateInstance with Enum in Constructor.

### ISSUE THREAD

**Issue by PedroHFranco** [moq/Moq.AutoMocker#103]
I'm using CreateInstance to call a Validator class and this validator has some variables in constructor, one of then is an enum.
When i'm using this enum i'm gotting a **TypeLoadException**.

> System.ArgumentException : GenericArguments[0], 'CrossCutting.NotaFiscal.Enums.EnumFinalidadeNota', on 'Moq.Mock`1[T]' violates the constraint of type 'T'.
>     ---- System.TypeLoadException : GenericArguments[0], 'CrossCutting.NotaFiscal.Enums.EnumFinalidadeNota', on 'Moq.IMock`1[T]' violates the constraint of type parameter 'T'.

I'm creating a Fixture to control the mocker.

```
[CollectionDefinition(nameof(NotaFiscalUnitTestCollection))]
public class NotaFiscalUnitTestCollection : ICollectionFixture<NotaFiscalUnitTestFixture> { }
public class NotaFiscalUnitTestFixture : IDisposable
{
	public readonly AutoMocker Mocker;
	private NotaFiscalMaterialValidator _notaFiscalMaterialValidator;

	public NotaFiscalUnitTestFixture()
	{
		Mocker = new AutoMocker();
	}

	public NotaFiscalMaterialValidator GetNotaFiscalMaterialValidator()
	{
		if (_notaFiscalMaterialValidator == null)
			_notaFiscalMaterialValidator = Mocker.CreateInstance<NotaFiscalMaterialValidator>();
		return _notaFiscalMaterialValidator;
	}

	public void Dispose()
	{
	}
}
```

My enum:

```
public enum EnumFinalidadeNota
{
	[Description("NF-e Normal")]
	Normal = 1,

	[Description("NF-e Complementar")]
	Complementar = 2,

	[Description("NF-e de Ajuste")]
	Ajuste = 3,

	[Description("Devolucao de mercadoria")]
	DevolucaoMercadoria = 4
}
```

And my NotaFiscalMaterial Validator

```
public class NotaFiscalMaterialValidator : ValidatorEntityBase<Domain.Entities.NotaFiscalMaterial>
{
	private readonly EnumFinalidadeNota _finalidadeNota;
	private readonly bool? _operacaoMovimentaEstoque;
	public NotaFiscalMaterialValidator(IServiceGlobalization globalization, EnumFinalidadeNota finalidadeNota, bool? operacaoMovimentaEstoque) : base(globalization)
	{
		_finalidadeNota = finalidadeNota;
		_operacaoMovimentaEstoque = operacaoMovimentaEstoque;
	}        
}
```

I'm using Moq.AutoMocker in 

> version 2.3.0.0

Any idea what might be causing this exception?

**Comment by adamhewitt627** [comment]
Sorry for the delay. Due to a bug we aren't giving the most helpful error here since it attempts to create a `Mock<EnumFinalidadeNota>` which fails because enums are `sealed` and thus can't actually be mocked. We _should_ be telling you we can't find a mock-able constructor.

You would need to provide a default value, something like:
```cs
Mocker = new AutoMocker();
Mocker.Use(EnumFinalidadeNota.Normal);
Mocker.Use(false); //For the operacaoMovimentaEstoque
```
