### ISSUE TITLE
Expose a way to iterate over all resolved objects (i.e. expose `typeMap`)

### ISSUE THREAD

**Issue by ascott18** [moq/Moq.AutoMocker#108]
I have a set of integration tests that span over a wide set of services. These services utilize the Microsoft.Extensions.Logging infrastructure for logging, and as such, each different service injects its own variant of a logger in the form of an `ILogger<TService>`.

If I want to write assertions/verifications that no errors were logged by any of the services in the integration tests, I have to manually write the following for every possible logger variant (and hope I don't miss any):

``` c#
Mocker.Verify<ILogger<ServiceOne>>(l => l.Log(
    LogLevel.Error, 
    It.IsAny<EventId>(), 
    It.Is<It.IsAnyType>((o, _) =>true), 
    It.IsAny<Exception>(),
    It.Is<Func<It.IsAnyType, Exception, string>>((v, t) => true)),
    Times.Never()
);
Mocker.Verify<ILogger<ServiceTwo>>(l => l.Log(
    // ...
);
// and so on
```

I'd like to be able to iterate over all the objects that AutoMocker has created for me, use reflection to determine if the type of each is an `ILogger`, and then manually inspect the `.Invocations` of the mock to perform the verification. I see that this is all stored in `typeMap`, but doesn't seem to be exposed in any way.

**Comment by Keboo** [comment]
Another common usage I have wanted is disposing all IDisposable items. This is something I have wanted for a while as well
