### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ropez** [moq/Moq.AutoMocker#109]
Is there any documentation available for this package?

**Comment by Keboo** [comment]
Currently not much beyond what is in the README. Part of that comes from the how small the API started out, but as it has grown it could certainly use more.

What sort of things were you hoping to find?

**Comment by ropez** [comment]
@Keboo Thanks for the quick response.

One of the things I wondered about, was the following:

I have a group of classes that I want to test together. They each have different dependencies that are dependency injected at runtime. One of the classes, say the `Facade`, has dependencies of each of the other classes, in addition to other dependencies. I was looking for a way to set up automocker, so that when I say `CreateInstance` for the `Facade` class, it would use concrete instances of the specific classes that I want to test together, and generate mocks for everything else.

I found a way to do this, which seems to work OK:

```csharp
var automocker = new AutoMocker();
automocker.Use<InterfaceA>(mocker.CreateInstance<ConcreteA>());
automocker.Use<InterfaceB>(mocker.CreateInstance<ConcreteB>());

var subject = automocker.CreateInstance<Facade>();
```

This works fine, but I was looking if there was something built in, along the lines of:

```csharp
automocker.UseConcrete<InterfaceA, ConcreteA>();
```

Looking for such methods, I saw that there was a `Combine` method, but I couldn't find any documentation for it, and it wasn't obvious to me what it means.

_More generally, coming into .NET after having more experience in other communities such as Python and Javascript, it seems to be that documentation is much less prioritized in .NET projects. For instance, for the testing framework XUnit, I haven't even found a documentation page that describe the different *Assert* methods that are available. I wonder why this is. Maybe it has something to do with the static typing and the IDE support, and people are relying on this "IntelliSense" thing as a replacement for documentation._

**Comment by Keboo** [comment]
In terms of your specific example, yes you did find the easiest way to handle it (using the `.Use` method). I find on my projects I tend to create [extension methods](https://docs.microsoft.com/dotnet/csharp/programming-guide/classes-and-structs/extension-methods) on AutoMocker to make it easy to setup my AutoMocker instance with the relevant concrete classes included. 
There is a slightly more advanced API as well you can use to accomplish the same task by going through the `AutoMocker.Resolvers` collection and adding in your own `IMockResolver`. These resolvers get called whenever a dependency is not explicitly registered with the `AutoMocker` instance, and provide a convenient callback where you can perform any logic you wish you build up an instance.

I can agree with your sentiment about a lack of documentation in the .NET eco system. My (albeit narrow) opinion is that some of it has been historical. Microsoft's push to move all things .NET to open source is relatively recent (4-5ish years). This certainly doesn't excuse all of the third party open source projects, but my opinion is people tend to follow the leader. There is also a strong push to rely on IntelliSense; however I would agree that it only goes so far. It is great when you want to get information on the specifics of a function, but that method is certainly lacking when it comes to the discovery of what is in a library.

However, this long explanation does speak to your original point that this repository is lacking in documentation. I think what we should do is start a docs folder in the repo and start building the documentation there. This is inline with what the [main moq repo](https://github.com/moq/moq/tree/main/docs) is doing. Older projects have leveraged the wiki on GitHub, however that lack the convenience of pull requests to review documentation changes.
@adamhewitt627 or @tkellogg thoughts on this? I am thinking at minimum, it would be good to get some markdown files with some basic descriptions/explanations for the public API. Long term I think it would be nice to look at doing something a bit fancier and sync some of the XML comment stuff into the markdown pages just so things don't drift.

**Comment by Keboo** [comment]
@ropez I also added #110 to try and account for the desired workflow that you put above. Would love your feedback on it.

**Comment by ropez** [comment]
@Keboo Wow 👏

Thanks for the elaborate explanation, and for taking actions 👍
