### ISSUE TITLE
Get<T> versus CreateInstance<T> methods

### ISSUE THREAD

**Issue by BrainCrumbz** [moq/Moq.AutoMocker#18]
What's the difference between [`CreateInstance<T>`](https://github.com/tkellogg/Moq.AutoMocker/blob/664327ac0fc74fe264378473742905a580f22882/Moq.AutoMock/AutoMocker.cs#L36) and [`Get<T>`](https://github.com/tkellogg/Moq.AutoMocker/blob/664327ac0fc74fe264378473742905a580f22882/Moq.AutoMock/AutoMocker.cs#L176) methods? 

Looking at the source code or the readme it is not quite clear.
TA

**Comment by tkellogg** [comment]
Get just retrieves a mock that was stored in the container. CreateInstance uses the container to build a real object with constructor args mocked out.

**Comment by BrainCrumbz** [comment]
Thanks for quick reply. Questions:

1. Is it right to say that `Get` should be used with dependencies, while `CreateInstance` should be used for the *System Under Test*?

1. What would `Get` return if no mock was stored in the container for the requested Type?

**Comment by Keboo** [comment]
This is very old, but for anyone coming accross it.

1. Yes, `Get` can be thought of as a way to retrieve mocked dependencies, while `CreateInstance` is usually what is used to create the system under test.
2. `Get` will either return the stored mock or create and store a new mock of the request type.
