### ISSUE TITLE
TypeLoadException for Castle.Core.Internal.CollectionExtensions after updating from v3.4.0 to v3.5.0

### ISSUE THREAD

**Issue by MelGrubb** [moq/Moq.AutoMocker#200]
After updating Moq.AutoMocker from v3.4.0 to v3.5.0, I'm getting an exception in my test suite. I have isolated it to this one change. The git diff contains only the updated package reference. There are no other changes pending. I can change 3.5 to 3.4 and my tests run again. Without including too much of my test/project, here's the exception I'm seeing at runtime.

`Expected: <System.ComponentModel.DataAnnotations.ValidationException>
  But was:  <System.TypeLoadException: Could not load type 'Castle.Core.Internal.CollectionExtensions' from assembly 'Castle.Core, Version=5.0.0.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc'.`

**Comment by Keboo** [comment]
Hi @MelGrubb 

This looks like it might be an issue with transitive nuget dependencies. 
Can you run `dotnet list <YourTestProject> package` and share the results?

**Comment by MelGrubb** [comment]
I'm working on a different branch today, but I'll try to get back to this. It's definitely a transitive dependency though. It took me a few passes to figure out which top level package was pulling in a new Castle.Core version and eventually isolated it to Moq.Automocker. Every other package in the project is up to date, and everything works fine. Updating Moq.Automocker updates Castle.Core, and they seem to have removed some thing in the "Internal" namespace from public view.

**Comment by Keboo** [comment]
Thank you @MelGrubb 

Can you take a look at this sample project. I tried to replicate your setup but was unable to successfully replicate the issue. I suspect it is likely a conflict with some assembly loading of one of the other dependencies. 

[Example.zip](https://github.com/moq/Moq.AutoMocker/files/11268521/Example.zip)

**Comment by MelGrubb** [comment]
I can run the sample project and tests just fine. Also, it's only two specific tests in my suite that fail under v3.5.0, while the rest work as normal. That means it's some weird drug interaction with something else that's specific to us, I guess. This may not be a "you" problem. I'll update if I find the cause.

**Comment by Keboo** [comment]
Sounds good. If there is any more information you can find out, I am happy to revisit it.

**Comment by Keboo** [comment]
Closing for now. If you find any more details @MelGrubb feel free to re-open.
