### ISSUE TITLE
Are are the docs hosted anywhere?

### ISSUE THREAD

**Issue by michaelo-numerik** [moq/Moq.AutoMocker#202]
I see that there some (auto-generated?) docs in https://github.com/moq/Moq.AutoMocker/tree/master/docs. Are these hosted anywhere? I couldn't find any from some basic Googling.

**Comment by Keboo** [comment]
At present no, they just exist as markdown files at that path.

**Comment by michaelo-numerik** [comment]
Righto, cheers.
