### ISSUE TITLE
InjectAttribute

### ISSUE THREAD

**Issue by kuhnboy** [moq/Moq.AutoMocker#236]
How do I have Moq work with Blazor's Razor @inject attribute or [Inject] so that the proper dependencies are injected upon Create<>?

**Comment by Keboo** [comment]
I think this more hinges on your testing framework and less on AutoMocker. 

For example if you are using something like bUnit, it supports adding in an `IServiceProvider` (as seen here: https://bunit.dev/docs/providing-input/inject-services-into-components.html). `AutoMocker` also implements the `IServiceProvider` interface so you could it is in place of where those samples show `FallbackServiceProvider`
