### ISSUE TITLE
Support for Primary Constructors

### ISSUE THREAD

**Issue by dilvid83** [moq/Moq.AutoMocker#268]
Hi there,

Currently Primary Constructors do not work for CreateInstance.

Take the following snippet

```
public class MyManager
{
    private readonly ISomeInferface _someInterface;

    public MyManager(ISomeInterface someInterface)
    {
        _someInterface = someInterface;
    }

    public void test()
    {
        _someInterface.DoSomething();
    }
}
```

The above works...now we swap over to a Primary Constructor...

```
public class MyManager(ISomeInterface someInterface)
{
    public void test()
    {
        someInterface.DoSomething();
    }
}
```

And this doesn't work. It doesn't seem to recognise that it needs to inject in an 'ISomeInterface' when using a primary constructor. It remains null.

**Comment by Keboo** [comment]
@dilvid83 what version of the library are you using?

Using Moq.AutoMock version 3.5.0 and Moq version 4.20.69, the following works:

```C#
public class AMTests
{
    [Fact]
    public void Test1()
    {
        //Arrange
        AutoMocker mocker = new();
        mocker.Setup<ISomeInterface>(x => x.DoSomething()).Verifiable();

        var sut = mocker.CreateInstance<MyManager>();

        //Act
        sut.test();

        //Assert
        mocker.Verify();
    }

    [Fact]
    public void Test2()
    {
        //Arrange
        AutoMocker mocker = new();
        mocker.Setup<ISomeInterface>(x => x.DoSomething()).Verifiable();

        var sut = mocker.CreateInstance<MyManager2>();

        //Act
        sut.test();

        //Assert
        mocker.Verify();
    }
}

public interface ISomeInterface
{
    void DoSomething();
}

public class MyManager
{
    private readonly ISomeInterface _someInterface;

    public MyManager(ISomeInterface someInterface)
    {
        _someInterface = someInterface;
    }

    public void test()
    {
        _someInterface.DoSomething();
    }
}

public class MyManager2(ISomeInterface someInterface)
{
    public void test()
    {
        someInterface.DoSomething();
    }
}
```

I also opened PR: #269 to with tests covering `CreateInstance` on types with primary constructors.

**Comment by dilvid83** [comment]
Sorry for the delay in response. I do have the latest versions.

I'll dig a little deeper into what is going on in my instance. 

What I have is a mocked context (using Moq.EntityFrameworkCore) which is then added via the 'Use' function. I then create an instance of the repository which again is added via the 'Use' function and lastly I create an instance of the object I want to test. This works fine sometimes....perfectly. However sometimes it just doesn't want to work unless I swap the constructor from a primary constructor to the standard constructor pattern. Hence why I thought it wasn't supported.

This is an example of what I have..


Test Class
```
public class BarcodeManagerTests
{
    private AutoMocker _autoMocker = new AutoMocker();
    private Mock<SweatAndSacrificeContext> _mockContext;
    
    [SetUp]
    public void SetUp()
    {
        _autoMocker = new AutoMocker();
        _mockContext = new Mock<MyContext>();
        ContextHelper.AddDbSets(ref _mockContext);
        
        _autoMocker.Use<MyContext>(_mockContext.Object);
        _autoMocker.Use<IOptions<ApiSettings>>(OptionsHelper.GetSettings);
    }

    [TestCase("22A8EB72-F4F9-40E6-A210-BAF7AF732F40",  "1234567890", "764AD7C9-6D42-466E-B137-8A4D38990F7D")]
    public async Task AddBarcode_Tests(string regardingId, string barcode, string countryId)
    {
        //Arrange
        var countryEntity = Country.Data.Single(c => c.CountryId == countryId.ToGuid());
        
        var barcodeRepository = _autoMocker.CreateInstance<BarcodeRepository>();
        
        _autoMocker.Use<IBarcodeRepository>(barcodeRepository);

        var barcodeManager = _autoMocker.CreateInstance<BarcodeManager>();
        _autoMocker.VerifyAll();

        //Act
        var result = await barcodeManager.AddBarcode(regardingId.ToGuid(), barcode, countryId.ToGuid());
        
        //Assert
        result.Should().NotBeNull();
        result.CountryId.ToString().Should().Be("764AD7C9-6D42-466E-B137-8A4D38990F7D");
        result.Barcode.Should().Be(barcode);
        result.CountryName.Should().Be(countryEntity.Name);
        result.RegardingId.Should().Be(regardingId);
    }
}
```

Manager Class
```

public class BarcodeManager(ILogger<BarcodeManager> log, IOptions<ApiSettings> apiSettings, IBarcodeRepository barcodeRepository) 
    : BaseManager(log, apiSettings), IBarcodeManager
{
    public async Task<BarcodeModel> AddBarcode(Guid regardingId, string barcode, Guid countryId)
    {
        var barcodeEntity = await barcodeRepository.GetBarcode(barcode, countryId, regardingId);

        if (barcodeEntity == null)
        {
            barcodeEntity = new BarcodeEntity
            {
                Barcode = barcode,
                CountryId = countryId,
                DateCreated = DateTime.UtcNow,
                DateModified = DateTime.UtcNow,
                RegardingId = regardingId
            };

            await barcodeRepository.Create(barcodeEntity);

            barcodeEntity = await barcodeRepository.GetBarcode(barcode, countryId, regardingId);
        }

        return new BarcodeModel
        {
            Barcode = barcodeEntity!.Barcode,
            BarcodeId = barcodeEntity!.BarcodeId,
            CountryId = barcodeEntity!.CountryId,
            CountryName = barcodeEntity.Country.Name,
            RegardingId = barcodeEntity.RegardingId,
            RegardingType = barcodeEntity.RegardingType
        };
    }
}
```

Repository Class

```
public class BarcodeRepository(MyContext db) : IBarcodeRepository
{
    public async Task<BarcodeEntity> Create(BarcodeEntity barcodeEntity)
    {
        barcodeEntity.DateCreated = DateTime.UtcNow;
        barcodeEntity.DateModified = DateTime.UtcNow;

        await db.Barcodes!.AddAsync(barcodeEntity);

        await db.SaveChangesAsync();

        return barcodeEntity;
    }    
    
    public async Task<BarcodeEntity?> GetBarcode(string barcode, Guid countryId, Guid regardingId)
    {
        var result = await db.Barcodes!.Include("Country").SingleOrDefaultAsync(be => be.Barcode == barcode 
                                                                    && be.CountryId == countryId 
                                                                    && be.RegardingId == regardingId);

        return result;
    }
}
```

**Comment by Keboo** [comment]
Thanks for the follow up. From that code you have provided, I don't see anything that shouldn't be supported or wouldn't work. Which specific line in that example do you see fail?

**Comment by dilvid83** [comment]
Hi there,

It doesn't fail as in an exception during creating a Mock etc. It attempts to perform the test fine however when It goes into the 'Manager' class  'barcodeRepository' is null. 

The strange thing is that inside the test I can call the instantiated Barcode Repository, call the same function the Manager does and it hits the Mocked context fine there. It just doesn't seem to recognise that the instance created is the one to pass through.

Does that make sense?

**Comment by dilvid83** [comment]
Hi there,

I've managed to recreate it in a new project. I kept all my structures etc the same to see if it's something with my layout etc...

[https://github.com/dilvid83/automockissue](https://github.com/dilvid83/automockissue)

**Comment by Keboo** [comment]
Thank you for the sample repository. Looking over the failure it looks like there are a few issues.

1. The `Some.Data` does not specify anything for the `Country` property. This appears to be the source of the null reference exception being caused.
Something like this:
```C#
new SomeEntity
{
    DateCreated = DateTime.Today,
    DateModified = DateTime.Today,
    DateDeleted = null,
    Info = "4088600079332",
    Country = new() 
    { 
        CountryId = "764AD7C9-6D42-466E-B137-8A4D38990F7D".ToGuid(),
        Name = "United Kingdom"
    },
    CountryId = "764AD7C9-6D42-466E-B137-8A4D38990F7D".ToGuid(),
    RegardingId = "2E8B8FD8-82D4-4C89-9D14-CF0A005867A5".ToGuid(),
    SomeModelId = "220A5668-2C99-4EA1-8887-3060944059F6".ToGuid()
}
```
2. It looks like there is also an assertion issue with the way Guids are being compared. When parsing a guid from a string and back again, the casing is different. For example this test **fails**:
```C#
[TestCase]
public void Guids()
{
    string guidString = "2E8B8FD8-82D4-4C89-9D14-CF0A005867A5";
    guidString.ToGuid().ToString().Should().Be(guidString);
}
```
This is the reason why this assert is failing. `result.CountryId.ToString().Should().Be("764AD7C9-6D42-466E-B137-8A4D38990F7D");`

**Comment by dilvid83** [comment]
Hey,

The ToGuid method, that is just me being lazy :). You can't (nicely) do a TestCase and pass in a guid so I pass in a string and convert to a guid.

I think you are right. I think the null repo is a 'red herring' with the UI. As you can see from my image the repo is being shown as NULL however managed to return data. Combining what you've said about the country object and the error o 'Object reference not found' I think seeing the NULL lead me to believe it was that the instance wasn't fulfilled. 

Thank you
<img width="839" alt="Screenshot 2024-01-21 at 08 13 01" src="https://github.com/moq/Moq.AutoMocker/assets/35134326/1a45a4b7-dc2c-4c20-b836-4cc1a2216969">
