### ISSUE TITLE
Change license

### ISSUE THREAD

**Issue by Keboo** [moq/Moq.AutoMocker#42]
Should we update the license file in the project to the standard MIT license so that it matches moq?

**Comment by tkellogg** [comment]
I'd prefer that we keep the license the same unless we have specific instances where the license is blocking people from using Moq.AutoMocker. I don't see any advantages to MIT over Apache 2, but we could cause some issues by changing the license unexpectedly. Probably not worth it.

However, I think it might be appropriate to install [CLA Bot](https://github.com/clabot/clabot) to ensure that contributors have signed off on a contributor license agreement.

**Comment by tkellogg** [comment]
Sure, I like that idea

**Comment by adamhewitt627** [comment]
Further discussion suggests the compatibility of Apache 2 with GPL is "debatable." https://twitter.com/martinwoodward/status/1007093868809113600 Let's go ahead and switch to MIT.

**Comment by tkellogg** [comment]
To be clear, we’re switching to MIT because it’s important that everyone feels the freedom to use this library and it seems insane to disallow open source projects from using it. LGTM
