### ISSUE TITLE
Stubbing Values?

### ISSUE THREAD

**Issue by jpreese** [moq/Moq.AutoMocker#58]
Lets say I have a class with 3 dependencies.. `A`, `B` and `C`. If Dependency `A` has an `async` method on it that I would like to change the return value of, how is that accomplished with this library?

Using vanilla Moq, you would do something like that following.

```
var a = new Mock<A>();
a.SetUp(s => s.MyMethod()).ReturnsAsync("some value");

var b = new Mock<B>();
var c = new Mock<C>();

var systemUnderTest = new SystemUnderTest(a.Object, b.Object, c.Object);
```

With AutoMocker..?

**Comment by Keboo** [comment]
This AutoMocker library is more of an extension of Moq so the same API for interacting with Mocks still works. The key difference is you don't need to create the `Mock<>` objects or the system under test directly.
I would probably write your unit test this way.

```C#
var mocker = new AutoMocker();

var a = mocker.GetMock<A>();
a.SetUp(s => s.MyMethod()).ReturnsAsync("some value");

var systemUnderTest = mocker.CreateInstance<SystemUnderTest>();
```

**Comment by adamhewitt627** [comment]
Also an option is the convenience methods with doing the setup on the mocker directly. Although, especially coming from vanilla Moq, @Keboo's answer is probably an easier move, both for changes and for mental overhead.

```C#
var mocker = new AutoMocker();
mocker.Setup<A>(s => s.MyMethod()).ReturnsAsync("some value");

var systemUnderTest = mocker.CreateInstance<A>();
```

**Comment by jpreese** [comment]
Alright, I'll have to put together a sample project and give that a go. I recall when trying yesterday I couldn't find a ReturnsAsync() method. I'm not even sure if I recall seeing a Returns method.

**Comment by adamhewitt627** [comment]
It took me a while to get used to that one too, but `ReturnsAsync` is an extension method from `Moq`. When using `Mock<T>` as in your first example, you get the import automatically, while the AutoMocker code requires importing it.

```
using Moq;

//tests
```

**Comment by jpreese** [comment]
Alright, in a brand new project, all of the suggestions above do seem to work. So this can probably be closed. Thanks guys!

As a quick aside, I was originally drawn to this library since we have an ASP.NET MVC app which consist of controllers, and a lot of the controllers have a lot of dependencies.. 10+ isn't uncommon. It's a huge pain to get a test suite for a given class up and running. Obviously, it's a bit smelly, and we should probably find ways to group those dependencies so the consumer has fewer interfaces, but it's just not the world we're in.

After playing with this, it makes the instantiation way simpler, but I almost feel like it hides too much. From my experience, most dependencies will need to be stubbed anyway, but taking an AutoMock route, you don't know what those dependencies are. If you were to remove a dependency, the test would still have the stub and continue to work, rather than break. Though some would see this as a boon to have more "resilient" tests.
