### ISSUE TITLE
NETStandard.Library is referenced in NuGet

### ISSUE THREAD

**Issue by SH2015** [moq/Moq.AutoMocker#59]
It cause to install a lot of assemblies , please remove it from .nuspec file .

**Comment by Keboo** [comment]
@SH2015 can you provide more information. What is the target framework of your project? Do you get the same behavior if you simply include Moq?

[Moq](https://www.nuget.org/packages/Moq/) itself has similar dependencies depending on TargetFramework. The solution here would be multi-targeting with different dependencies for .NET Framework 4.5.

**Comment by SH2015** [comment]
@Keboo : I am using .Net 4.7 , already have Moq referenced , but this package install a lot of references that doesn't seem to be used (as per Re-sharper ). and I had to rollback the installation because of the ammount of dependencies was installed. 
Logically if Moq works in 4.7 then this should work too without installing another library

**Comment by SH2015** [comment]
@Keboo  : any update?

**Comment by stakx** [comment]
Just FYI, I'm looking at having additional framework targets added to the Moq library. People have been complaining about the excessive number of dependencies caused by .NET Standard 1.3 vs .NET Standard 2.0. Moq will likely get `netstandard2.0` and `net461` targets in the next minor release.

**Comment by Keboo** [comment]
@stakx awesome that is good to hear.
