### ISSUE TITLE
GetMock<T>() != GetMock(Type t) for Interfaces

### ISSUE THREAD

**Issue by masanek** [moq/Moq.AutoMocker#63]
We are trying to register mocks for all interfaces when using the .net Core Test Host. We are using reflection to make this easier.

(sudo code below)
var types = GetAssemblywithInterfaces().Types;
foreeach( Type t in types)
servicecollection.Register(mocker.GetMock(t).Object);
^ this throws exceptions as t is an interface and not a class.

This does not work where as if we individual register each interface explicitly via
servicecollection.Register(mocker.GetMock<IInterface>().Object)
it works as expected

It seems there is a generic type constrainton GetMock<T>  Where T : Class 
https://github.com/moq/Moq.AutoMocker/blob/master/Moq.AutoMock/AutoMocker.cs#L263

This is not equivalent to
https://github.com/moq/Moq.AutoMocker/blob/master/Moq.AutoMock/AutoMocker.cs#L274

from the microsoft documentation
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/constraints-on-type-parameters 
It seems where T : class restricts reference types not specifically "class" objects

defect? or should we not be doing our workflow

**Comment by Keboo** [comment]
Looks like a bug to me. PR sent out for it.
