### ISSUE TITLE
SetupSequence shortcut

### ISSUE THREAD

**Issue by lasrol** [moq/Moq.AutoMocker#66]
I created a method on the AutoMocker for SetupSequence. I think its a "nice to have" shortcut, when adding a sequence of results. 

Are you interested in a PR for it?

**Comment by Keboo** [comment]
Yea I would be interested in taking a look at it. If it is really just a "nice to have" it might work better as an extension method, but will need to take a look to know for sure.

**Comment by lasrol** [comment]
Added PR for you to consider :)

**Comment by Keboo** [comment]
Closing since PR has been merged.
