### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by alex-fomin** [moq/Moq.AutoMocker#68]

**Comment by Keboo** [comment]
Yep though though there has been little need to make many advancements. Are you running into any issues?

**Comment by alex-fomin** [comment]
It is impossible to provide non-mocked parameters to `CreateInstance<T>()` method. For instance, my ctor has string argument, and i get NotSupportedException (Type to mock must be an interface or an abstract or non-sealed class).
If project is activa I'll prepare pull request to fix the issue,

**Comment by Keboo** [comment]
Yes, happy to review a PR and get it merged
