### ISSUE TITLE
Is there a way to register factory methods?

### ISSUE THREAD

**Issue by kennethcochran** [moq/Moq.AutoMocker#69]
I'm attempting to use AutoMocker to do some limited scope integration tests. Component tests if you will. Some dependencies I don't care about so they are automatically resolved to mocks. Others I need to be concrete instances. But many of these concrete dependencies have dependencies of their own, which again some are important others are not. I'm currently setting up the test fixtures like so:

```
            var mocker = new AutoMocker();
            mocker.Use<IDependency1>(mocker.CreateInstance<Dependency1>());
            mocker.Use<IDependency2>(mocker.CreateInstance<Dependency2>());
            mocker.Use<IDependency3>(mocker.CreateInstance<Dependency3>());
            mocker.Use<IDependency4>(mocker.CreateInstance<Dependency4>());

            this.SUT = mocker.CreateInstance<SystemUnderTest>();
```
The problem I'm having is that CreateInstance<T> is called immediately and if Dependency3 has a dependency on Dependency4 it is getting a mock instead. So the order of Use<T> is highly dependent on which dependencies need to be concrete. Being able to register a factory method like
`mocker.Use<IDependency>(x => mocker.CreateInstance<Dependency>());`
would allow the creation to be delayed until all the dependencies have been registered.

Of course there could already be a way to do what I'm asking and I'm just not aware of it. If so, can you point me in the right direction?

**Comment by Keboo** [comment]
@kennethcochran it is certainly possible though the API is not very discoverable. We should probably consider adding a new API to do lazy resolution. Letting the Use method take in a delegate add some ambiguity when the SUT takes in a delegate as a dependency. 

Now for the solution. The latest version of AM allows you to add arbitrary resolver classes that can be used as factories to create instances. So for you case, something like this should work:
```
[TestMethod]
public void TestMethod1()
{
    var mocker = new AutoMocker();

    mocker.Resolvers.Add(new Resolver<IDependency1, Dependency1>());
    mocker.Resolvers.Add(new Resolver<IDependency2, Dependency2>());

    var sut = mocker.CreateInstance<SystemUnderTest>();
}

public class Resolver<TDependency, TImplementation> : IMockResolver where TImplementation : class
{
    public void Resolve(MockResolutionContext context)
    {
        if (context.RequestType == typeof(TDependency))
        {
            context.Value = context.AutoMocker.CreateInstance<TImplementation>();
        }
    }
}

public class SystemUnderTest
{
    public SystemUnderTest(IDependency1 dependency1, IDependency2 dependency2)
    {

    }
}

public interface IDependency1 { }
public class Dependency1 : IDependency1
{
    public Dependency1(IDependency2 dependency2)
    { }
}

public interface IDependency2 { }
public class Dependency2 : IDependency2
{

}
```

It might be nice to make this a bit more discoverable and add a some sort of `.LazyCreateInstance`, will have to consider what the best API is for that.

**Comment by Keboo** [comment]
Closing for now unless there are followup questions.
