### ISSUE TITLE
Support for nullable value types

### ISSUE THREAD

**Issue by mu88** [moq/Moq.AutoMocker#74]
When using nullable value types like `int?`, the verification has to be written in the form of `autoMocker.GetMock<IService>().Verify<int?>()`. As far as I see, this is due to the generic constraint `where TResult : struct` in `public void Verify<T, TResult>(Expression<Func<T, TResult>> expression, Func<Times> times)`.

It would be nice to write it more concisely: `autoMocker.Verify<IService, int?>()`. Do you see any change for that?

**Comment by Keboo** [comment]
There is a nullable reference type branch that is being worked on that I believe will address this.

**Comment by Keboo** [comment]
Fixed with the latest nullable stuff getting merged.
