### ISSUE TITLE
Is it possible to register Factory Delegates for ViewModel testing

### ISSUE THREAD

**Issue by blankenshipmq10k** [moq/Moq.AutoMocker#75]
Currently facing an issue where I need to use CreateInstance on a ViewModel that is constructed using a factory delegate from the IoC.

Wiring up the use statements as such will allow the tests to execute, but with the way the type mappings are setup there is not a way to have multiple registrations for types and have them change - i.e. string.

            _mocker.Use<EnumType>(EnumType.Value1);
            _mocker.Use<int>(38);
            _mocker.Use<string>("test1");
            _mocker.Use<string>("test2");
            _mocker.Use<string>("test3");

            _mocker.CreateInstance<ReallyCoolViewModel>();

Any help and/or suggestions would be greatly appreciated!

**Comment by Keboo** [comment]
This is similar to the question posed in #69 

There is an API, though it is not very discoverable, through the Resolvers collection. With it you can register an arbitrary resolver that is capable of doing custom resolution for types. I assume the situation that you have with your view model, is that its constructor takes in a mixture of value types (strings, int, enums, etc), and dependencies (which I suspect you want mocked).

Building on the example there, I would probably suggest doing something like this:
```C#
[TestMethod]
public void TestMethod1()
{
    var mocker = new AutoMocker();

    mocker.Resolvers.Add(new Resolver("foo", 42, EnumType.Value1));
    var sut = mocker.CreateInstance<ReallyCoolViewModel>();
}

public class Resolver : IMockResolver where T : class
{
    public Resolver(string str, int number, EnumType type)
    {
        _str = str;
        _number = number;
        _type = type;
    }

    public void Resolve(MockResolutionContext context)
    {
        if (context.RequestType == typeof(ReallyCoolViewModel))
        {
            context.Value = new ReallyCoolViewModel(_str, _number, _type, context.AutoMocker.Get<IDependency>(), context.AutoMocker.Get<IDependency2>());
        }
    }
}
```

Depending on how many places you need the resolver, it may also be easier to move the logic into a helper method.
