### ISSUE TITLE
Can't Resolve IEnumerable<Tservice>

### ISSUE THREAD

**Issue by DAud-IcI** [moq/Moq.AutoMocker#76]
Some of our code uses `IEnumerable<Tservice>` in the constructor to return all registered services. When I use `mocker.CreateInstance` on such a class, it gets created fine. The corresponding field is not null and seems to be an `IEnumerable<Tservice>` but when I try to enumerate, it throws a NullReferenceException inside. The same happens regardless if I register Tservice with `mocker.Use`.

The only workaround I could manage was to hardcode the values like `mocker.Use<IEnumerable<IServiceA>>(new[] { mocker.CreateInstance<ServiceA>() });` or `mocker.Use<IEnumerable<IServiceA>>(Array.Empty<IServiceA>())` if it's not needed. 
Am I doing something wrong?

The exception is this, there is no InnerException.

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at AutomockTester.Program.Main()
```

It can be reproduced like this:

```C#
using Microsoft.Extensions.DependencyInjection;
using Moq.AutoMock;
using System;
using System.Collections.Generic;
using System.Linq;

namespace AutomockTester
{
    public interface IServiceA { int Value { get; } }
    public interface IServiceB { IEnumerable<int> Values { get; } }

    public class ServiceA  : IServiceA { public int Value { get; } = 42; }
    public class ServiceB : IServiceB
    {
        readonly IEnumerable<IServiceA> _services;
        public IEnumerable<int> Values => _services.Select(x => x.Value);
        public ServiceB(IEnumerable<IServiceA> services) { _services = services; }
    }

    class Program
    {
        static void Main()
        {
            var services = new ServiceCollection();
            services.AddSingleton<IServiceA, ServiceA>();
            services.AddSingleton<IServiceB, ServiceB>();
            foreach (var n in services.BuildServiceProvider().GetService<IServiceB>().Values)
                Console.WriteLine("Value: {0}", n);

            var mocker = new AutoMocker();
            // I have to hardcore IEnumerable<IServiceA> in the line below...
            //mocker.Use<IEnumerable<IServiceA>>(new[] { mocker.CreateInstance<ServiceA>() });
            var service = mocker.CreateInstance<ServiceB>();
            // ... otherwise it crashes here at the "in".
            foreach (var n in service.Values)
                Console.WriteLine("Value: {0}", n);
        }
    }
}
```

**Comment by Keboo** [comment]
Hi @DAud-IcI 

This is unfortunately a Moq issues and not an AutoMocker problem. You will note that you see identical behavior if you do:
```C#
var items = Mock.Of<IEnumerable<IService1>>();
items.Any();
```

As for your work around, explicitly registering something with `.Use` would be the correct way to handle this.

**Comment by adamhewitt627** [comment]
@DAud-IcI, here is a little more detail. I ran into this myself recently and it helped me to know why a null reference would show up.

This code:
```cs
foreach (var n in enumerableService)
    Console.WriteLine("Value: {0}", n);
```

Is roughly equivalent to this, after the compiler is done with it:
```cs
using (var enumerator = enumerableService.GetEnumerator())
{
    while (enumerator.MoveNext())    //Oops, NullReferenceException!
    {
        var n = enumerator.Current;
        Console.WriteLine("Value: {0}", n);
    }
}
```

Moq, by default, sets up methods to return default values. The mocked `IEnumerable` is non-null, but its `GetEnumerator` returns null without any additional `Use` or `Setup` calls.

**Comment by basharat58** [comment]
Try something like this:
```
var service1 = new Mock< IServiceA>();
var service2 = new Mock< IServiceA>();

Mocker.Use(new []{ service1.Object, service2.Object }.AsEnumerable());
```
Think that should do it.

**Comment by DAud-IcI** [comment]
Thank you very much for the help. Now I understand the situation much better.
