### ISSUE TITLE
[Feature request] Implement IServiceProvider

### ISSUE THREAD

**Issue by StevenLiekens** [moq/Moq.AutoMocker#89]
Hi,

I'm in a situation where I inherited some code that uses the service locator pattern, ie.

``` csharp
public class LegacyService
{
    private readonly IServiceProvider _serviceLocator;

    public LegacyService(IServiceProvider sl) => _serviceLocator = sl;

    public void LegacyCodeUnderTest()
    {
         var dep1 = _serviceLocator.GetService(typeof(DataSource));
         var dep2 = _serviceLocator.GetService(typeof(EmailGateway));
         var html = FormatEmail(dep1.Stuff);
         dep2.Send(html);
    }

    private string FormatEmail(object[] data) { ... }
}
```

I'm refactoring away from this pattern, but in the meantime I'd still like to use AutoMocker to provide mixed fake and real instances of dependencies to the class under test. Is it possible to make the _AutoMocker_ class implement _IServiceProvider_?

**Comment by Keboo** [comment]
What is possible is to make your own class that derives from AutoMocker and implements IServiceProvider.
```C#
public class AutoMockerEx : AutoMocker, IServiceProvider
{
    public object GetService(Type serviceType) => CreateInstance(serviceType);
}
```

The real difficulty here is deciding if calls to GetService should invoke CreateInstance, Get, or GetMock. You may have to adjust the implementation on GetService to suit your particular code base.

**Comment by StevenLiekens** [comment]
You're right, deciding if GetService should return a mock or a real instance requires context. I was thinking it should always call _CreateInstance_ but on second thought that's not what I want.
